### ISSUE TITLE
No updates made on Hours of Operation 

### ISSUE THREAD

**Issue by rsanuvala** [aws-samples/amazon-connect-copy#3] opened 2022-04-25 17:14 UTC
Hi Jacky,

We used the same scripts to do Connect Copy from one AWS Account to different AWS account. We observed the below:
a) The source instance  has 3 Hours of Operation{AA, BB, IvrHrs} and Target has 3 {AA, FF, TestEnvIvrHrs}. AA on source has multiple entries configured and target AA has no entries. we were expecting the target AA to be updated with multiple entries same as source AA, but that's not happening. We don't see any values in helper.old file since these are updates. Can you please suggest?

b) We also don't see IvrHrs getting created in target instance. Just wondering if the script looks for any partial match as target has TestEnvIvrHrs? 

Thanks
Raji

**Comment by kjacky** [comment] 2022-04-28 23:53
Thank you Raji for your report.

a) The issue has been fixed in the latest merge.
b) The script does not do partial match unless you specify a prefix. I believe the issue is related to a).

Please download the latest version and let me know if the issues persist.

Thanks
Raji

**Closed by kjacky** 2022-04-28 23:53 UTC
